import type { Metadata } from "next";
import { Prompt } from 'next/font/google'
import "./globals.css";

const prompt = Prompt({
  subsets: ['latin', 'thai'],
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const locale = "en";

  return (
    <html lang={locale}>
      <body className={`${prompt.className} font-normal antialiased`}>
        {children}
      </body>
    </html>
  );
}
