import type { Metadata } from "next";
import MainLayout from "@/component/layout/mainLayout";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ locale: "en" }, { locale: "th" }, { locale: "ja" }];
}

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  let messages = {};
  try {
    messages = (await import(`../../locales/${locale}.json`)).default;
  } catch (e) {
    messages = (await import(`../../locales/en.json`)).default;
  }
  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <MainLayout>{children}</MainLayout>
    </NextIntlClientProvider>
  );
}
